# Generated by Django 5.0.6 on 2026-05-20 14:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0005_system_health"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("company", models.CharField(blank=True, max_length=200)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[("home", "Home"), ("business", "Business")],
                        default="home",
                        max_length=8,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("referral", "Referral"),
                            ("website", "Website"),
                            ("social", "Social"),
                            ("inbound_email", "Inbound email"),
                            ("cold", "Cold outreach"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("source_detail", models.CharField(blank=True, max_length=200)),
                ("interest", models.TextField(blank=True)),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("quoted", "Quoted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("dormant", "Dormant"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("next_action_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("lost_reason", models.CharField(blank=True, max_length=200)),
                ("last_reminded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "converted_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_leads",
                        to="clients.client",
                    ),
                ),
                (
                    "referring_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("quote_sent", "Quote sent"),
                            ("stage_change", "Stage change"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["stage"], name="leads_lead_stage_4b0a5d_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["next_action_at"], name="leads_lead_next_ac_9e6a40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadactivity",
            index=models.Index(
                fields=["lead", "-occurred_at"], name="leads_leada_lead_id_f724f0_idx"
            ),
        ),
    ]
