# Generated by Django 5.0.6 on 2026-06-10 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_credit_note"),
        ("clients", "0016_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "due_date"], name="billing_inv_status_996e80_idx"
            ),
        ),
    ]
