# Generated by Django 5.0.6 on 2026-04-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('care_plan_tier', models.CharField(choices=[('none', 'None'), ('essential', 'Essential'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='none', max_length=16)),
                ('care_plan_start', models.DateField(blank=True, null=True)),
                ('care_plan_renewal', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('network', 'Network'), ('automation', 'Home Automation'), ('website', 'Website'), ('app', 'Mobile App'), ('security', 'Security / CCTV')], max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('devices_json', models.JSONField(blank=True, default=dict)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('monitoring_url', models.URLField(blank=True)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='clients.client')),
            ],
            options={
                'ordering': ['client__name', 'name'],
            },
        ),
    ]
