# Generated by Django 5.0.6 on 2026-05-20 20:03

import django.db.models.deletion
from django.db import migrations, models

import clients.models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_referralcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="NpsResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=clients.models._nps_token, max_length=64, unique=True
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("quarter_label", models.CharField(max_length=12)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nps_responses",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "unique_together": {("client", "quarter_label")},
            },
        ),
    ]
