# Generated by Django 5.0.6 on 2026-06-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_client_status_page_slug"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="healthsample",
            new_name="clients_hea_system__9343a4_idx",
            old_name="clients_hea_system__9a8c6f_idx",
        ),
        migrations.AlterField(
            model_name="client",
            name="care_plan_tier",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("essential", "Essential"),
                    ("professional", "Professional"),
                    ("enterprise", "Enterprise"),
                ],
                db_index=True,
                default="none",
                max_length=16,
            ),
        ),
    ]
