# Generated by Django 5.0.6 on 2026-05-18 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0004_maintenance_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin_page", "LinkedIn Page"),
                            ("facebook_page", "Facebook Page"),
                            ("instagram_business", "Instagram Business"),
                        ],
                        max_length=24,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("avatar_url", models.URLField(blank=True)),
                ("access_token_encrypted", models.TextField(blank=True)),
                ("refresh_token_encrypted", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.CharField(blank=True, max_length=500)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "health_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Unknown"),
                            ("ok", "OK"),
                            ("degraded", "Degraded"),
                            ("down", "Down"),
                        ],
                        max_length=16,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("followers", models.IntegerField(blank=True, null=True)),
                ("followers_7d_ago", models.IntegerField(blank=True, null=True)),
                ("last_post_at", models.DateTimeField(blank=True, null=True)),
                ("kpis_json", models.JSONField(blank=True, default=dict)),
                ("last_overdue_alert_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["platform"],
            },
        ),
        migrations.CreateModel(
            name="SocialInboxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dm", "Direct message"),
                            ("mention", "Mention"),
                            ("comment", "Comment"),
                        ],
                        max_length=12,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("author_handle", models.CharField(blank=True, max_length=200)),
                ("author_display", models.CharField(blank=True, max_length=200)),
                ("preview", models.TextField(blank=True)),
                ("permalink", models.URLField(blank=True, max_length=1000)),
                ("received_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("dismissed", "Dismissed"),
                            ("converted", "Converted to ticket"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox",
                        to="social.socialaccount",
                    ),
                ),
                (
                    "converted_ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_inbox_items",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="socialaccount",
            constraint=models.UniqueConstraint(
                fields=("platform", "external_id"),
                name="uniq_social_account_platform_external",
            ),
        ),
        migrations.AddIndex(
            model_name="socialinboxitem",
            index=models.Index(
                fields=["account", "status", "-received_at"],
                name="social_inbox_top_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="socialinboxitem",
            constraint=models.UniqueConstraint(
                fields=("account", "external_id"),
                name="uniq_social_inbox_account_external",
            ),
        ),
    ]
