# Generated by Django 5.0.6 on 2026-05-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_devicetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("ticket_update", "Ticket update"),
                    ("sla_warning", "SLA warning"),
                    ("system_alert", "System alert"),
                    ("new_ticket", "New ticket"),
                    ("social_alert", "Social account alert"),
                ],
                max_length=20,
            ),
        ),
    ]
